name: Release

on:
  push:
    branches:
      - master

jobs:
  check-version:
    # Ensures that the current version is later than the one on the marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get package info
        id: packageInfo
        run: |
          echo "::set-output name=extension_publisher::$(jq -r '.publisher' package.json)"
          echo "::set-output name=extension_name::$(jq -r '.name' package.json)"
          echo "::set-output name=extension_version::$(jq -r '.version' package.json)"
      - name: Check version validity
        uses: lhl2617/vsce-version-check-action@v1.0.0
        with:
          extension-publisher: ${{ steps.packageInfo.outputs.extension_publisher }}
          extension-name: ${{ steps.packageInfo.outputs.extension_name }}
          extension-version: ${{ steps.packageInfo.outputs.extension_version }}

  release:
    runs-on: ubuntu-latest
    needs:
      - check-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Publish extension
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
